### YamlMime:ModuleUnit
uid: learn.introduction-to-security.5-network-security
title: <span data-ttu-id="c38bd-101">保护你的网络</span><span class="sxs-lookup"><span data-stu-id="c38bd-101">Protect your network</span></span>
metadata:
  title: <span data-ttu-id="c38bd-102">保护你的网络</span><span class="sxs-lookup"><span data-stu-id="c38bd-102">Protect your network</span></span>
  description: <span data-ttu-id="c38bd-103">在此单元中, 我们将讨论如何保护您的网络基础结构。</span><span class="sxs-lookup"><span data-stu-id="c38bd-103">In this unit, we'll discuss how to secure your network infrastructure.</span></span>
  ms.date: 12/26/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: 36ba32d0c5367b690bc8aa9f7f82071fa6fab9ad
  ms.sourcegitcommit: ed6fdf0be4f20279586c4d18c9105fdb65a392eb
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/21/2019
  ms.locfileid: "2136517"
durationInMinutes: 8
content: '[!include[](includes/5-network-security.md)]'
